### PR TITLE
Feat/est hi res

### PR DESCRIPTION
**Pull request by abarciauskas-bgse**
I added a section to define what we mean by "high resolution", or at least at what resolution you might want to consider chunking + pyramiding your dataset.

... I would definitely like to refine this in the future. For example, I modeled performance (https://github.com/developmentseed/tile-benchmarking/blob/feat/working-on-modelling/02-run-tests/app-code-model.ipynb) and then created a widget for exploring how different chunk sizes + number of spatial chunks would impact performance in https://github.com/developmentseed/tile-benchmarking/blob/feat/working-on-modelling/02-run-tests/predict-tile-times.ipynb. But I am not confident in those model estimates so decided not to add it to the report yet.

I added PR previews so you can view the content at https://nasa-impact.github.io/zarr-visualization-report/pr-preview/pr-29/approaches/tiling/recommendations.html

### CODE REVIEW

**Comment by wildintellect** [comment]
@abarciauskas-bgse when it says:
`1448.0 latitude x 2896.0 longitude` the units on that is cells? so really this is length of columns and rows and each cell represents `Meters at the equator: 76.649 x 38.435`? Use of Latitude and Longitude there is somewhat confusing since your talking about the x and y dimension lengths of the array (just happen to be doing a global data which corresponds to geographic).

Where do 110,000 and 111,320 come from? 
```
print(f"* Meters at the equator: {np.round(111000/lat_dim, 3)} x {np.round(111320/lon_dim, 3)}\n")
```

**Comment by maxrjones** [comment]
> If your dataset has a higher resolution than what is listed above, you will either want to chunk your data spatially or create a pyramid or both. Having spatially chunked data can also impact performance at low zoom, so you should try chunks significantly smaller than 8MB, say 4MB. Assuming the spatial extent of your data is larger than 16MB, you will probably want to create a pyramid.

I think it would be worthwhile to mention in this paragraph that it's common to prefer larger chunk sizes for analysis workflows, which would motivate creating pyramids with small chunks for visualization purposes. In addition, it might be worthwhile to mention the potential of Zarr V3 sharding extension to help in the future with the trade-off between chunk size and number of chunks at different zoom levels, especially given the potential to concatenate adjacent ranges into a single request.

**Comment by abarciauskas-bgse** [comment]
@wildintellect @maxrjones thanks for your feedback, it is very welcomed. I have addressed both comments in https://github.com/NASA-IMPACT/zarr-visualization-report/pull/29/commits/bee4e05c47a2ecd9bc2d7a279d30a382290e5d53 let me know if it's improved.

**Comment by wildintellect** [comment]
@abarciauskas-bgse So this is a 1 x 1 degree tile? something feels odd about not having a single approximate resolution, but have a different x and y value. Usually there's 2x longitude because it's 360 degrees vs latitude of 180 degrees. Also when going to units less than a degree it's more common to use Degree based notation for global data ( 1 degree = 60 minutes = 3600 seconds), or round to less precision (looks like on CMIP doc 2 decimals is common so things round to .25 which people comprehend)

To give examples, from WordClim which does global layers:
> 30 seconds (~1 km2), 10 minutes (~340 km2)

And from an CMIP6 page
> 1.25° latitude x 2.5° longitude (<- looks like some are rectangular, but at a ratio of 1:2, so each pixel is still square)
> 2.8° latitude x 2.8° longitude
https://climatedata.ca/resource/cmip6-faq/#:~:text=The%20latest%20version%20of%20this,latitude%20x%202.5%C2%B0%20longitude.

(Edit): Trying to put this into a suggestion...
Start with Total Memory/dtype = Number of Cells, then split number of cells into a 2:1 Long:Lat ratio, then calculate actual meters or Km based on common tile sizes like 1 degree or 30 second to arrive at a single meters/km number. This highlights that given a desired/known resolution you could infer how much can be stored in a chunk, and therefore how many chunks would be needed to cover a total area of known size.

(Edit2) Ah you're trying to operate off a Global dataset <- that needs to be stated clearly.

**Comment by abarciauskas-bgse** [comment]
Yes, I'm assuming the pixels are square which is why there are twice as many values in the longitude (x) dimension as the latitude (y) dimension. 

I acknowledge the conversion to km was wrong, since it should be equivalent distances at the equator for latitude and longitude. I previously came across an equation for calculating the km squared for degrees (not haversine) but I can't find it so I'm just removing that calculation for now.

**Comment by wildintellect** [comment]
@abarciauskas-bgse I think I pushed a fix to the resolution calculation, and bolded **global** in the text. If it looks good to you then we can approve this.

**Comment by abarciauskas-bgse** [comment]
Lgtm, thanks @wildintellect

**Review by maxrjones — APPROVED** [review]
Nice!

**Pull request merged**
